from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class ProcessingProfile:
    name: str
    description: str
    target_height: int
    target_fps: float
    denoise_strength: int
    sharpen_strength: float
    grain_strength: float
    use_deband: bool
    upscale_backend: str
    interpolation_backend: str
    upscale_model: str
    interpolation_model: str
    encoder: str
    cq_value: int
    temporal_strength: float = 0.0


PROFILES = {
    "Fast FFmpeg 720p30": ProcessingProfile(
        name="Fast FFmpeg 720p30",
        description="Szybki preset HD do lekkiego upscale i 30 fps bez AI.",
        target_height=720,
        target_fps=30.0,
        denoise_strength=1,
        sharpen_strength=0.08,
        grain_strength=0.0,
        use_deband=False,
        upscale_backend="ffmpeg",
        interpolation_backend="minterpolate",
        upscale_model="realesrgan-x4plus",
        interpolation_model="rife-v4.6",
        encoder="h264_nvenc",
        cq_value=19,
        temporal_strength=0.0,
    ),
    "Fast FFmpeg 720p60": ProcessingProfile(
        name="Fast FFmpeg 720p60",
        description="HD 60 fps bez AI, dobry do starszych gameplayow i materialow web.",
        target_height=720,
        target_fps=60.0,
        denoise_strength=1,
        sharpen_strength=0.08,
        grain_strength=0.0,
        use_deband=False,
        upscale_backend="ffmpeg",
        interpolation_backend="minterpolate",
        upscale_model="realesrgan-x4plus",
        interpolation_model="rife-v4.6",
        encoder="h264_nvenc",
        cq_value=19,
        temporal_strength=0.0,
    ),
    "Fast FFmpeg 1080p30": ProcessingProfile(
        name="Fast FFmpeg 1080p30",
        description="Prosty preset Full HD przy 30 fps, gdy nie chcesz agresywnej interpolacji.",
        target_height=1080,
        target_fps=30.0,
        denoise_strength=1,
        sharpen_strength=0.1,
        grain_strength=0.0,
        use_deband=False,
        upscale_backend="ffmpeg",
        interpolation_backend="minterpolate",
        upscale_model="realesrgan-x4plus",
        interpolation_model="rife-v4.6",
        encoder="h264_nvenc",
        cq_value=18,
        temporal_strength=0.0,
    ),
    "Balanced 4K60": ProcessingProfile(
        name="Balanced 4K60",
        description="4K60 z bezpieczniejszym, naturalnym pipeline'em.",
        target_height=2160,
        target_fps=60.0,
        denoise_strength=2,
        sharpen_strength=0.2,
        grain_strength=0.0,
        use_deband=True,
        upscale_backend="realesrgan",
        interpolation_backend="minterpolate",
        upscale_model="realesrgan-x4plus",
        interpolation_model="rife-v4.6",
        encoder="hevc_nvenc",
        cq_value=18,
        temporal_strength=0.18,
    ),
    "Local AI VSR 4K60": ProcessingProfile(
        name="Local AI VSR 4K60",
        description="Pelny lokalny stack: Real-ESRGAN, temporal restore i RIFE, bez chmury i bez fallbackowego upscale.",
        target_height=2160,
        target_fps=60.0,
        denoise_strength=2,
        sharpen_strength=0.18,
        grain_strength=0.02,
        use_deband=True,
        upscale_backend="realesrgan",
        interpolation_backend="rife",
        upscale_model="realesrgan-x4plus",
        interpolation_model="rife-v4.6",
        encoder="hevc_nvenc",
        cq_value=17,
        temporal_strength=0.32,
    ),
    "AI Restore 4K60": ProcessingProfile(
        name="AI Restore 4K60",
        description="Mocniejszy tryb AI z Real-ESRGAN i RIFE, jesli narzedzia sa zainstalowane.",
        target_height=2160,
        target_fps=60.0,
        denoise_strength=3,
        sharpen_strength=0.25,
        grain_strength=0.05,
        use_deband=True,
        upscale_backend="realesrgan",
        interpolation_backend="rife",
        upscale_model="realesrgan-x4plus",
        interpolation_model="rife-v4.6",
        encoder="hevc_nvenc",
        cq_value=17,
        temporal_strength=0.4,
    ),
    "Archive Natural 1440p60": ProcessingProfile(
        name="Archive Natural 1440p60",
        description="Mniej agresywny preset dla starych materialow i archiwow.",
        target_height=1440,
        target_fps=60.0,
        denoise_strength=2,
        sharpen_strength=0.1,
        grain_strength=0.08,
        use_deband=True,
        upscale_backend="ffmpeg",
        interpolation_backend="minterpolate",
        upscale_model="realesrgan-x4plus",
        interpolation_model="rife-v4.6",
        encoder="hevc_nvenc",
        cq_value=18,
        temporal_strength=0.22,
    ),
    "Anime 4K60": ProcessingProfile(
        name="Anime 4K60",
        description="Preset pod anime/cartoon z animevideov3 i opcjonalnym RIFE.",
        target_height=2160,
        target_fps=60.0,
        denoise_strength=1,
        sharpen_strength=0.15,
        grain_strength=0.0,
        use_deband=True,
        upscale_backend="realesrgan",
        interpolation_backend="rife",
        upscale_model="realesr-animevideov3",
        interpolation_model="rife-v4.6",
        encoder="h264_nvenc",
        cq_value=16,
        temporal_strength=0.12,
    ),
    "Fast FFmpeg 1080p60": ProcessingProfile(
        name="Fast FFmpeg 1080p60",
        description="Dziala od razu bez AI tools; dobra opcja startowa.",
        target_height=1080,
        target_fps=60.0,
        denoise_strength=1,
        sharpen_strength=0.1,
        grain_strength=0.0,
        use_deband=False,
        upscale_backend="ffmpeg",
        interpolation_backend="minterpolate",
        upscale_model="realesrgan-x4plus",
        interpolation_model="rife-v4.6",
        encoder="h264_nvenc",
        cq_value=18,
        temporal_strength=0.0,
    ),
    "AI Lift 720p30": ProcessingProfile(
        name="AI Lift 720p30",
        description="Lokalny AI upscale do HD i 30 fps dla slabszego lub bardziej problematycznego zrodla.",
        target_height=720,
        target_fps=30.0,
        denoise_strength=2,
        sharpen_strength=0.12,
        grain_strength=0.0,
        use_deband=True,
        upscale_backend="realesrgan",
        interpolation_backend="rife",
        upscale_model="realesrgan-x4plus",
        interpolation_model="rife-v4.6",
        encoder="h264_nvenc",
        cq_value=18,
        temporal_strength=0.18,
    ),
    "AI Lift 1080p30": ProcessingProfile(
        name="AI Lift 1080p30",
        description="Lokalny AI upscale do Full HD przy 30 fps, naturalniejszy od bardziej agresywnych presetow.",
        target_height=1080,
        target_fps=30.0,
        denoise_strength=2,
        sharpen_strength=0.12,
        grain_strength=0.02,
        use_deband=True,
        upscale_backend="realesrgan",
        interpolation_backend="rife",
        upscale_model="realesrgan-x4plus",
        interpolation_model="rife-v4.6",
        encoder="h264_nvenc",
        cq_value=18,
        temporal_strength=0.2,
    ),
    "AI Lift 1080p60": ProcessingProfile(
        name="AI Lift 1080p60",
        description="Mocniejszy lokalny preset Full HD i 60 fps z lepszym cleanupem starego materialu.",
        target_height=1080,
        target_fps=60.0,
        denoise_strength=2,
        sharpen_strength=0.14,
        grain_strength=0.02,
        use_deband=True,
        upscale_backend="realesrgan",
        interpolation_backend="rife",
        upscale_model="realesrgan-x4plus",
        interpolation_model="rife-v4.6",
        encoder="h264_nvenc",
        cq_value=17,
        temporal_strength=0.25,
    ),
    "Gameplay Clean 1080p60": ProcessingProfile(
        name="Gameplay Clean 1080p60",
        description="Preset pod stare gry i capture, z lekka redukcja szumu i ostrzejszym ruchem.",
        target_height=1080,
        target_fps=60.0,
        denoise_strength=1,
        sharpen_strength=0.14,
        grain_strength=0.0,
        use_deband=False,
        upscale_backend="ffmpeg",
        interpolation_backend="minterpolate",
        upscale_model="realesrgan-x4plus",
        interpolation_model="rife-v4.6",
        encoder="h264_nvenc",
        cq_value=18,
        temporal_strength=0.0,
    ),
}


IMAGE_PROFILES = {
    "Photo Restore HAT 4x": {
        "description": "Domyslny najlepszy preset do zdjec: HAT z bardziej wiernym detalem i lekkim liftingiem koloru.",
        "image_scale": 4,
        "upscale_backend": "hat",
        "upscale_model": "real_hat_gan",
        "denoise_strength": 1,
        "sharpen_strength": 0.12,
        "brightness": 1.01,
        "contrast": 1.04,
        "saturation": 1.03,
        "gamma": 1.0,
        "auto_contrast": True,
        "image_output_format": "png",
    },
    "Photo Restore HAT Sharper 4x": {
        "description": "Mocniejszy i ostrzejszy HAT do bardziej efektownego upscale, kosztem naturalnosci.",
        "image_scale": 4,
        "upscale_backend": "hat",
        "upscale_model": "real_hat_gan_sharper",
        "denoise_strength": 1,
        "sharpen_strength": 0.18,
        "brightness": 1.01,
        "contrast": 1.05,
        "saturation": 1.03,
        "gamma": 1.0,
        "auto_contrast": True,
        "image_output_format": "png",
    },
    "Photo Lift 4x": {
        "description": "Pelny lifting zdjec z AI upscale 4x i lekkim color boostem.",
        "image_scale": 4,
        "upscale_backend": "realesrgan",
        "upscale_model": "realesrgan-x4plus",
        "denoise_strength": 1,
        "sharpen_strength": 0.15,
        "brightness": 1.02,
        "contrast": 1.06,
        "saturation": 1.04,
        "gamma": 1.0,
        "auto_contrast": True,
        "image_output_format": "png",
    },
    "Gentle Batch 2x": {
        "description": "Lagodny batch upscale 2x z bezpieczniejsza korekcja koloru.",
        "image_scale": 2,
        "upscale_backend": "realesrgan",
        "upscale_model": "realesrgan-x4plus",
        "denoise_strength": 0,
        "sharpen_strength": 0.1,
        "brightness": 1.0,
        "contrast": 1.02,
        "saturation": 1.02,
        "gamma": 1.0,
        "auto_contrast": False,
        "image_output_format": "png",
    },
    "Anime Clean 4x": {
        "description": "Preset pod ilustracje i anime z anime model i czystym outputem.",
        "image_scale": 4,
        "upscale_backend": "realesrgan",
        "upscale_model": "realesrgan-x4plus-anime",
        "denoise_strength": 0,
        "sharpen_strength": 0.1,
        "brightness": 1.0,
        "contrast": 1.03,
        "saturation": 1.01,
        "gamma": 1.0,
        "auto_contrast": False,
        "image_output_format": "png",
    },
}
